### ISSUE TITLE
Seems like it doesn't work

### ISSUE THREAD

**Issue by ozasadnyy** [social-elements/gplus-elements#12]
I am not sure but it seems like element doesn't work.
http://zenorocha.github.io/gplus-elements/

**Comment by Nevraeka** [comment]
@zenorocha should we migrate the demo over to the org?

**Comment by zenorocha** [comment]
it was "migrated" already (http://social-elements.github.io/gplus-elements/), it's just not working

**Comment by Nevraeka** [comment]
:+1: @zenorocha . Thanks I'll take a look

**Comment by Nevraeka** [comment]
@zenorocha @ozasadnyy should be fixed now

**Comment by zenorocha** [comment]
:+1:
